services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # تغییر پورت
      - "443:443"  # تغییر پورت
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - flask-app
